name: deploy dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: syn-api-dev
          heroku_email: metagabbar@gmail.com
          usedocker: true
        env:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
